apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weather-service
  namespace: knativetutorial
spec:
  template:
    spec:
      container:
        image: __IMAGE__
        env:
          - name: WEATHER_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: weather-api
                key: token
