apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: weather-service
  namespace: knativetutorial
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: __IMAGE__
