apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weather-service
  namespace: knativetutorial
spec:
  template:
    metadata:
      name: weather-service-1
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: __IMAGE__
          imagePullPolicy: Always
          env:
            - name: WEATHER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: weather-api
                  key: token
